alias btcdir='cd /home/ubuntu/.bitcoin/' #linux default bitcoind path
alias bc='bitcoin-cli'
alias bd='bitcoind'
alias btcinfo='bitcoin-cli getwalletinfo | egrep "\"balance\""; bitcoin-cli getnetworkinfo | egrep "\"version\"|connections"; bitcoin-cli getmininginfo | egrep "\"blocks\"|errors"'

export PS1='🐳  \[\033[1;36m\]\h \[\033[1;34m\]\W\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]'
source /etc/profile.d/bash_completion.sh
