services:
  bitcoin-core:
    build: .
    container_name: bitcoin-core
    volumes:
      - ./datadir:/root/.bitcoin
      - ./bash_profile:/root/.bash_profile
      - ../rpc-scavenger-hunt-dcadenas/submission/:/root/exercises
